apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-management
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s3-management
  template:
    metadata:
      labels:
        app: s3-management
    spec:
      containers:
      - name: s3-management
        image: entropypool/s3-management:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: s3-management
  namespace: kube-system
spec:
  ports:
  - name: api
    port: 50120
    targetPort: 50120
  - name: grpc
    port: 50121
    targetPort: 50121
  - name: prometheus
    port: 50122
    targetPort: 50122
  selector:
    app: s3-management